name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - stage
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: iam-roles-${{ github.event.inputs.environment || 'dev' }}
          template: templates/iam-roles.yml
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: "Environment=${{ github.event.inputs.environment || 'dev' }}"
          no-fail-on-empty-changeset: "1"
          tags: |
            {"ManagedBy":"GitHub-Actions","Repository":"${{ github.repository }}"}
